#!/bin/sh

host="$(hostname)"
os="Debian $(cat /etc/debian_version)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(dpkg -l | grep -c ^i)"
shell="$(basename "${SHELL}")"

parse_rcs() {
	for f in "${@}"; do
		wm="$(tail -n 1 "${f}" 2> /dev/null | cut -d ' ' -f 2)"
		[ -n "${wm}" ] && echo "${wm}" && return
	done
}

rcwm="$(parse_rcs "${HOME}/.xinitrc" "${HOME}/.xsession")"

ui='unknown'
uitype='UI'

if [ -n "${DE}" ]; then
	ui="${DE}"
	uitype='DE'
elif [ -n "${WM}" ]; then
	ui="${WM}"
	uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
	ui="${XDG_CURRENT_DESKTOP}"
	uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
	ui="${DESKTOP_SESSION}"
	uitype='DE'
elif [ -n "${rcwm}" ]; then
	ui="${rcwm}"
	uitype='WM'
elif [ -n "${XDG_SESSION_TYPE}" ]; then
	ui="${XDG_SESSION_TYPE}"
fi

ui="$(basename "${ui}")"

if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold 2> /dev/null)"
	black="$(tput setaf 0 2> /dev/null)"
	red="$(tput setaf 1 2> /dev/null)"
	green="$(tput setaf 2 2> /dev/null)"
	yellow="$(tput setaf 3 2> /dev/null)"
	blue="$(tput setaf 4 2> /dev/null)"
	magenta="$(tput setaf 5 2> /dev/null)"
	cyan="$(tput setaf 6 2> /dev/null)"
	white="$(tput setaf 7 2> /dev/null)"
	reset="$(tput sgr0 2> /dev/null)"
fi

lavender="$(printf '\033[38;2;180;190;254m')" # #b4befe
text="$(printf '\033[38;2;205;214;244m')" # #cdd6f4j

lc="${reset}${bold}${lavender}"
nc="${reset}${bold}${lavender}"
ic="${reset}${text}"
c0="${reset}${lavender}"
c1="${reset}${lavender}"

cat <<EOF

${c0}     ,---._   ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}   /\`  __  \\  ${lc}OS:        ${ic}${os}${reset}
${c0}  |   /    |  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}  |   ${c1}\`.__.\`  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}   \          ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}    \`-,_      ${lc}SHELL:     ${ic}${shell}${reset}
${c0}              ${lc}${uitype}:        ${ic}${ui}${reset}

EOF
