# ─── BASIC ───────────────────────────────────
unbind-key -a -T root

set -g prefix C-q

set -g pane-border-lines "single"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g focus-events on

set -g status-interval 5

bind -n M-s choose-tree -s
bind -n M-r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# ─── CONTROLS ────────────────────────────────
setw -g mode-keys vi
set -g mouse on

set -s escape-time 0

set -g history-limit 2000

bind -n M-y copy-mode
bind-key -n M-p paste-buffer
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy || xclip -in -selection clipboard"
bind -n M-/ copy-mode \; command-prompt -p "(search down)" "send -X search-forward '%%%'"
bind -n M-? copy-mode \; command-prompt -p "(search up)"   "send -X search-backward '%%%'"

# ─── WINDOWS ─────────────────────────────────
bind -n M-Enter new-window
bind -n M-c kill-pane
bind -n M-q kill-window
bind -n M-d detach
bind -n M-Q confirm-before -p "Kill entire session? (y/n)" kill-session

bind -n M-- split-window -v
bind -n M-v split-window -h

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-H resize-pane -L 5
bind -n M-L resize-pane -R 5
bind -n M-K resize-pane -U 3
bind -n M-J resize-pane -D 3

# ─── APPEARANCE ──────────────────────────────
set -g status on
set -g status-justify absolute-centre

set -g status-left-length 60
set -g status-right-length 120

setw -g pane-active-border-style "fg=#89b4fa"
setw -g pane-border-style "fg=#313244"
set -g mode-style "fg=black,bg=#B4D8FD"

set -g status-style "bg=#11111b,fg=#cdd6f4"
set -g window-status-format "#[bg=#313244,fg=#cdd6f4] #W #[default]"
set -g window-status-current-format "#[bg=#89b4fa,fg=#11111b,bold] #W #[default]"

# ─── PLUGINS ─────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

run '~/.config/tmux/plugins/tpm/tpm'
